package com.darkssh.client.ui.screens

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.ExperimentalLayoutApi
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.consumeWindowInsets
import androidx.compose.foundation.layout.imeAnimationTarget
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.layout.windowInsetsPadding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.Button
import androidx.compose.material3.Checkbox
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.RadioButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Slider
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import com.darkssh.client.ui.screens.viewmodel.GeneratePubkeyViewModel
import com.darkssh.client.util.PubkeyUtils

@OptIn(ExperimentalMaterial3Api::class, ExperimentalLayoutApi::class)
@Composable
fun GeneratePubkeyScreen(
    onNavigateBack: () -> Unit,
    modifier: Modifier = Modifier,
    viewModel: GeneratePubkeyViewModel = hiltViewModel(),
) {
    val isGenerating by viewModel.isGenerating.collectAsState()
    val error by viewModel.error.collectAsState()
    val generated by viewModel.generated.collectAsState()
    val snackbarHostState = remember { SnackbarHostState() }

    // State for form fields
    var nickname by remember { mutableStateOf("") }
    var selectedKeyType by remember { mutableStateOf(PubkeyUtils.KeyType.RSA) }
    var bits by remember { mutableIntStateOf(PubkeyUtils.getDefaultBits(PubkeyUtils.KeyType.RSA)) }
    var password by remember { mutableStateOf("") }
    var confirmPassword by remember { mutableStateOf("") }
    var unlockAtStartup by remember { mutableStateOf(false) }
    var confirmUse by remember { mutableStateOf(false) }

    // Update bits when key type changes
    LaunchedEffect(selectedKeyType) {
        bits = PubkeyUtils.getDefaultBits(selectedKeyType)
    }

    // Handle error messages
    LaunchedEffect(error) {
        error?.let {
            snackbarHostState.showSnackbar(it)
        }
    }

    // Navigate back when key is successfully generated
    LaunchedEffect(generated) {
        if (generated) {
            onNavigateBack()
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Generate SSH Key") },
                navigationIcon = {
                    IconButton(onClick = onNavigateBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
            )
        },
        snackbarHost = { SnackbarHost(snackbarHostState) },
        contentWindowInsets = WindowInsets.imeAnimationTarget,
        modifier = modifier,
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .consumeWindowInsets(innerPadding)
                .padding(innerPadding)
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .windowInsetsPadding(WindowInsets.imeAnimationTarget)
                .padding(16.dp),
        ) {
            // Nickname field
            OutlinedTextField(
                value = nickname,
                onValueChange = { nickname = it },
                label = { Text("Nickname") },
                placeholder = { Text("Enter a nickname for this key") },
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
                enabled = !isGenerating,
            )

            Spacer(modifier = Modifier.height(16.dp))

            // Key Type Selection
            Text(
                text = "Key Type",
                style = MaterialTheme.typography.titleMedium,
            )
            Spacer(modifier = Modifier.height(8.dp))

            KeyTypeOption(
                label = "RSA",
                selected = selectedKeyType == PubkeyUtils.KeyType.RSA,
                onClick = { selectedKeyType = PubkeyUtils.KeyType.RSA },
                enabled = !isGenerating,
            )
            KeyTypeOption(
                label = "DSA",
                selected = selectedKeyType == PubkeyUtils.KeyType.DSA,
                onClick = { selectedKeyType = PubkeyUtils.KeyType.DSA },
                enabled = !isGenerating,
            )
            KeyTypeOption(
                label = "ECDSA",
                selected = selectedKeyType == PubkeyUtils.KeyType.EC,
                onClick = { selectedKeyType = PubkeyUtils.KeyType.EC },
                enabled = !isGenerating,
            )
            KeyTypeOption(
                label = "Ed25519",
                selected = selectedKeyType == PubkeyUtils.KeyType.ED25519,
                onClick = { selectedKeyType = PubkeyUtils.KeyType.ED25519 },
                enabled = !isGenerating,
            )

            Spacer(modifier = Modifier.height(16.dp))

            // Bit Strength (only for RSA and ECDSA)
            if (!PubkeyUtils.isFixedBits(selectedKeyType)) {
                Text(
                    text = "Key Size: $bits bits",
                    style = MaterialTheme.typography.titleMedium,
                )
                Spacer(modifier = Modifier.height(8.dp))
                Slider(
                    value = bits.toFloat(),
                    onValueChange = { bits = it.toInt() },
                    valueRange = PubkeyUtils.getMinBits(selectedKeyType).toFloat()..PubkeyUtils.getMaxBits(selectedKeyType).toFloat(),
                    steps = when (selectedKeyType) {
                        PubkeyUtils.KeyType.RSA -> (PubkeyUtils.getMaxBits(selectedKeyType) - PubkeyUtils.getMinBits(selectedKeyType)) / 256 - 1
                        PubkeyUtils.KeyType.EC -> 2 // 256, 384, 521
                        else -> 0
                    },
                    modifier = Modifier.fillMaxWidth(),
                    enabled = !isGenerating,
                )
                Spacer(modifier = Modifier.height(16.dp))
            }

            // Password fields
            OutlinedTextField(
                value = password,
                onValueChange = { password = it },
                label = { Text("Password") },
                placeholder = { Text("Optional password to encrypt the key") },
                visualTransformation = PasswordVisualTransformation(),
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
                enabled = !isGenerating,
            )

            Spacer(modifier = Modifier.height(8.dp))

            OutlinedTextField(
                value = confirmPassword,
                onValueChange = { confirmPassword = it },
                label = { Text("Confirm Password") },
                visualTransformation = PasswordVisualTransformation(),
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
                isError = password.isNotEmpty() && confirmPassword.isNotEmpty() && password != confirmPassword,
                enabled = !isGenerating,
                supportingText = if (password.isNotEmpty() && confirmPassword.isNotEmpty() && password != confirmPassword) {
                    { Text("Passwords do not match", color = MaterialTheme.colorScheme.error) }
                } else null,
            )

            Spacer(modifier = Modifier.height(16.dp))

            // Options
            Row(
                verticalAlignment = Alignment.CenterVertically,
                modifier = Modifier
                    .fillMaxWidth()
                    .clickable(enabled = !isGenerating) {
                        unlockAtStartup = !unlockAtStartup
                    },
            ) {
                Checkbox(
                    checked = unlockAtStartup,
                    onCheckedChange = { unlockAtStartup = it },
                    enabled = !isGenerating && password.isBlank(), // Only allow if no password
                )
                Spacer(modifier = Modifier.width(8.dp))
                Text(
                    text = "Load key at startup",
                    color = if (password.isNotBlank()) {
                        MaterialTheme.colorScheme.onSurface.copy(alpha = 0.38f)
                    } else {
                        MaterialTheme.colorScheme.onSurface
                    },
                )
            }

            Row(
                verticalAlignment = Alignment.CenterVertically,
                modifier = Modifier
                    .fillMaxWidth()
                    .clickable(enabled = !isGenerating) {
                        confirmUse = !confirmUse
                    },
            ) {
                Checkbox(
                    checked = confirmUse,
                    onCheckedChange = { confirmUse = it },
                    enabled = !isGenerating,
                )
                Spacer(modifier = Modifier.width(8.dp))
                Text("Confirm before use")
            }

            Spacer(modifier = Modifier.height(24.dp))

            // Generate Button
            Button(
                onClick = {
                    viewModel.generateKey(
                        nickname = nickname,
                        keyType = selectedKeyType,
                        bits = bits,
                        password = password.takeIf { it.isNotBlank() },
                        confirmPassword = confirmPassword.takeIf { it.isNotBlank() },
                        unlockAtStartup = unlockAtStartup,
                        confirmUse = confirmUse,
                    )
                },
                enabled = !isGenerating && 
                    nickname.isNotBlank() && 
                    (password.isBlank() || password == confirmPassword),
                modifier = Modifier.fillMaxWidth(),
            ) {
                if (isGenerating) {
                    CircularProgressIndicator(
                        modifier = Modifier
                            .padding(end = 8.dp)
                            .width(16.dp)
                            .height(16.dp)
                    )
                }
                Text(if (isGenerating) "Generating..." else "Generate Key")
            }
        }
    }
}

@Composable
private fun KeyTypeOption(
    label: String,
    selected: Boolean,
    onClick: () -> Unit,
    enabled: Boolean = true,
) {
    Row(
        verticalAlignment = Alignment.CenterVertically,
        modifier = Modifier
            .fillMaxWidth()
            .clickable(enabled = enabled) { onClick() }
            .padding(vertical = 4.dp),
    ) {
        RadioButton(
            selected = selected,
            onClick = onClick,
            enabled = enabled,
        )
        Spacer(modifier = Modifier.width(8.dp))
        Text(
            text = label,
            color = if (enabled) {
                MaterialTheme.colorScheme.onSurface
            } else {
                MaterialTheme.colorScheme.onSurface.copy(alpha = 0.38f)
            },
        )
    }
}